get values 1

diff --git a/.github/workflows/test-coverage-local.yaml b/.github/workflows/test-coverage-local.yaml
--- a/.github/workflows/test-coverage-local.yaml
+++ b/.github/workflows/test-coverage-local.yaml
@@ -51,9 +51,10 @@ jobs:
         shell: bash
         run: |
           COV_PATCH=$(cat ${{ github.workspace }}/cov_patch.Rout)
-          echo "cov_patch=$COV_PATCH" >> $GITHUB_ENV
+          echo "::set-output name=cov_patch::$COV_PATCH"
           echo "cov_patch=$COV_PATCH"
           COV_CURRENT=$(cat ${{ github.workspace }}/cov_current.Rout)
+          echo "::set-output name=cov_current::$COV_CURRENT"
           echo "cov_current=$COV_CURRENT"
 
       - name: Checkout gh-pages
@@ -65,15 +66,24 @@ jobs:
         id: patch-comparison
         shell: bash
         run: |
-          cov_patch="${{ steps.get-values.outputs.cov_patch }}"
-          cov_current="${{ steps.get-values.outputs.cov_current }}"
-          
+          cov_patch="${{ env.cov_patch }}"
+          cov_current="${{ env.cov_current }}"
+
+          echo "cov_patch: $cov_patch"
+          echo "cov_current: $cov_current"
+
+          if [ -z "$cov_patch" ] || [ -z "$cov_current" ]; then
+            echo "Error: One or both of the coverage values is empty."
+            exit 1
+          fi
+
           if (( $(echo "$cov_patch >= $cov_current" | bc -l) )); then
             echo "Patch coverage ($cov_patch) is greater than or equal to current coverage ($cov_current)."
           else
             echo "Patch coverage ($cov_patch) is less than current coverage ($cov_current)."
             exit 1
           fi
+        shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
 
       - name: Overwrite cov_current.Rout
         uses: DamianReeves/write-file-action@master
